export const actionsEnums = {
  MEMBER_REQUEST: 'MEMBER_REQUEST',
  MEMBER_REQUEST_COMPLETED: 'MEMBER_REQUEST_COMPLETED',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  UPDATE_PAGE: 'UPDATE_PAGE',
  UPDATE_ROWS_PER_PAGE: 'UPDATE_ROWS_PER_PAGE',
  USER_REQUEST: 'USER_REQUEST',
  USER_REQUEST_COMPLETED: 'USER_REQUEST_COMPLETED',
}
