# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.box = "ubuntu/xenial64"
    server.vm.network "private_network", ip: "192.168.33.11"
    server.vm.provider "virtualbox" do |vb1|
      vb1.memory = "3000"
    end
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.box = "ubuntu/xenial64"
    client.vm.network "private_network", ip: "192.168.33.21"
    client.vm.provider "virtualbox" do |vb2|
      vb2.memory = "3000"
    end
  end

end
